### ISSUE TITLE
Post-specific pricing

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-typo3-extension#10]
As an admin,
I should be able to set individual prices for each piece of content in the Pay-per-Use and Single Sale revenue model,
so I have full flexibility in pricing my content.

**Comment by twoldrich** [comment]
_Further details:_

**Single Sale / Pay per Use**
The admin should be able to choose between the revenue model **PPU** (Pay per Use) and **SIS** (Single Sale)
- Between (including) **0.05** and (including) **1.48 EUR**, the revenue model should automatically be **PPU**. This should be indicated by a green "PPU" label next to the price input.
- Between (including) **1.49** and (including) **5.00 EUR**, the admin should be able to choose between **PPU** and **SIS** by clicking one of the two labels next to the price input. The **default** for this price range should be **PPU**. The chosen revenue model should be indicated by a green, the other revenue model by a grey label.
- Between (including) 5.01 and (including) 149.99 EUR, the revenue model should automatically be **SIS**. This should be indicated by a green "SIS" label next to the price input.
  ![pricing widget](https://cloud.githubusercontent.com/assets/6638286/6145875/a0330698-b1e6-11e4-9114-6d21191e0fd7.png)

**Validation**
The price in the pricing input must be **validated** (must be a price between 0.05 and 149.99 EUR).
Values **< 0.05** EUR should be corrected to **0.05** EUR, values **> 149.99** EUR should be set to **149.99** EUR.

**Default**
- By default, **new posts** should have a price of **0.29 EUR**.
- **Existing posts** should by default have a price of **0.29 EUR** after the first activation.

**Comment by yastapenko-ScnSoft** [comment]
Main problem that there are no possibilities in admin part of typo3 to change view in admin part. So it looks poor, nonetheless task seems like done.
