### ISSUE TITLE
Time passes

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-typo3-extension#11]
As an admin,
I should be able to create time passes, that grant access to the entire site or one selected category for a selected duration at a selected price (either as Pay-per-Use or Single Sale purchase),
so I can sell multiple pieces of content as a bundle for a limited amount of time (similar to a subscription, but without automatic renewal).

**Comment by twoldrich** [comment]
_Further details:_

**Appearance of time passes**
Time passes should by default look as shown on the following screenshots and contain the listed information:
![](https://cloud.githubusercontent.com/assets/6638286/3791770/12da7a44-1b53-11e4-9e55-d83f141e8ffe.png)

**Adding and editing time passes**
- There should be a section in the extension settings where the admin can create time passes, just as in the LaterPay WordPress Plugin: ![](https://cloud.githubusercontent.com/assets/6638286/3791848/ead4dc70-1b56-11e4-9194-08cd8f7c2c4a.jpg)
- When creating a new time pass, the following form should be displayed:
  ![new-time-pass](https://cloud.githubusercontent.com/assets/6638286/6144775/38c8c214-b1db-11e4-8ec1-320a89edd96a.png)

**Display of time passes**
- The list of time passes should always be displayed **below** a post.
- We should only display the time passes that are **relevant** in the current context:
- Example: There are three passes: **“Daypass Category News”**, **“Daypass Category Sport”** and **“Daypass Entire Blog”**. Within the category **news**, the user should see passes for **news** and the **entire blog**, but **not** for the category **sport**. Within the category **sport**, the user should see passes for **sport** and the **entire blog**, but **not** for the **category** news.
- The passes should be **sorted** as follows: First, (if available) passes for the **current category**, starting with the **lowest price** should be listed. Following them (if available), there should be passes for the **entire website**, starting with the **lowest price** as well.
- If a user **has already purchased** a time pass that is **valid in the current context**, the user should not see other time passes.

**Comment by yastapenko-ScnSoft** [comment]
@drdla Seems like pull request on this task was accepted, are some changes still needed or this task can be closed
