### ISSUE TITLE
Live and test mode

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-typo3-extension#12]
As an admin,
I should be able to switch between the live mode and a test mode that works against the LaterPay sandbox and where the extension is not visible to visitors of the site,
so I can test the plugin and tweak its configuration without a staging system.

**Comment by twoldrich** [comment]
_Further details:_

**Switching between live and test mode**
- There should be a toggle that allows the user to switch between live and test mode.
- To **be able to switch to live mode**, the admin must have entered valid **Live API credentials**, i.e. a **22** characters **Live Merchant ID** and a **32** characters **Live API Key**.
- If **no valid API credentials** are available, if the **Live API credentials are deleted**, or if they are **changed to invalid credentials**, the toggle should be set to "test mode" and be **disabled**.

**Default**
By default, the plugin should be in **test mode** after the first activation.

**Comment by yastapenko-ScnSoft** [comment]
@drdla what about visible test mode?
