### ISSUE TITLE
Caching compatibility

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-typo3-extension#15]
The extension should offer a caching compatible mode that recognizes popular caching solutions that cache data or entire HTML pages and can be manually switched into caching compatible mode from its settings page.
In caching compatible mode it should render only the preview content of paid content and check via Ajax, if a user has bought that piece of content and render that to the user.

**Comment by OlegHainulin-ScienceSoft** [comment]
For payable content cache must be disabled permanently

**Comment by drdla** [comment]
How is this compatible with caching then?

**Comment by OlegHainulin-ScienceSoft** [comment]
For payable pages we set front end no_cache flag, cache sub system of typo3 recognize this flag.

**Comment by OlegHainulin-ScienceSoft** [comment]
Frontend class tslib_fe have option
var $no_cache='';                   // Page will not be cached. Write only true. Never clear value (some other code might have reasons to set it true)
for payable pages we call method tslib_fe->set_no_cache(), payable pages will not be cached on condition of properly using of this option by another extentions

**Comment by drdla** [comment]
I still don't think simply turning off caching is a good idea, but let's leave it at that for the moment.
