### ISSUE TITLE
Logger + Dashboard

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-typo3-extension#16]
As an admin,
I should be able to view detailed statistics about page views, conversion rates, sales, and revenue,
so I can analyze the performance of my paid content.

The extension should track unique visitors and log all details about page views and purchases in a database table.

**Comment by twoldrich** [comment]
The spec for a sales dashboard can be found in the WordPress Plugin repository: https://github.com/laterpay/laterpay-wordpress-plugin/issues/86
