### ISSUE TITLE
Feed handling

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-typo3-extension#17]
As a user, admin, or crawler,
I should be able to view (RSS) feeds of the site, but only see an excerpt of the full content for paid content,
so I can stay updated on new content.

**Comment by yastapenko-ScnSoft** [comment]
@drdla typo3 from box haven't RSS feed. But there are some extensions which provide such functionality. So, is it needed to use such extension, or we need to create our own RSS feed mechanism?

**Comment by drdla** [comment]
Let's ignore this for the moment. If feeds are not built in, I expect it to be much harder to handle them. We should first check, if that is a required feature.
