### ISSUE TITLE
Automatic teaser content generation

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-typo3-extension#19]
The extension should automatically generate teaser content for paid content that does not have any teaser content defined by extracting a defined amount from the full content.
The automatic extraction should be defined by three parameters:
- percentage of content -> percentage of content to be extracted (values: 1-100); 20 means "extract 20% of the total number of words of the post"
- minimum word count -> MINimum number of words; applied if number of words as percentage of the total number of words is less than this value
- maximum word count -> MAXimum number of words; applied if number of words as percentage of the total number of words is greater than this value

**Comment by twoldrich** [comment]
_Further details:_

Teaser content should be created automatically, when an **existing** post **without teaser content (i.e. empty teaser)**
- is **displayed** to a visitor
- is **opened** for **editing**
- is **updated** with an **empty teaser**

or when a **new** post is saved with an **empty teaser**

If a user really wants to have an **empty teaser content**, he has to enter a space.

It should be possible to define the parameters for the **length of the teaser content** (see initial spec above) on the **settings page**.

**Comment by yastapenko-ScnSoft** [comment]
is opened for editing - this point in impossible to implement in typo3. So, excluding this one all other done
