### ISSUE TITLE
User role concept

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-typo3-extension#20]
The extension should have an authorization concept that grants specific viewing and editing rights to users based on their user role.

**Comment by twoldrich** [comment]
_Further details:_

For the WordPress Plugin, we defined clear capabilities for each **standard WordPress role**.
![](https://cloud.githubusercontent.com/assets/6638286/3373057/4ebeeb84-fbb0-11e3-90a6-92419d1522a4.png)

According to the documentation, it seems that Typo3 has **no standard roles** - the only standard (to be evaluated) seems to be the possibility to flag a user as **Admin**. So it has to be clarified if and how we could transfer our a roles and capabilities spec to Typo3.

**More information** about Typo3 users, groups and access control can be found here: http://docs.typo3.org/typo3cms/InsideTypo3Reference/CoreArchitecture/AccessControl/Index.html

**Comment by yastapenko-ScnSoft** [comment]
In typo3 exists two kind of users Frontend and Backend. This users are independent, i.e, you can be logged as admin in admin in backend and as user in user part at the same time. More of that - you even can't get BE user data from frontend by inner methods (except admin). And about plugin management -  them all configured in admin part from box. So about situation for now - the only user who can view and change display mode in user part - is admin. If that is enough than task done, else need to add some mechanisms to get BE data from FE part.

**Comment by drdla** [comment]
If that is how TYPO3 is working, we should leave it at that. Complicated workarounds are always a cause of severe headaches.
