### ISSUE TITLE
Set up test servers

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-typo3-extension#22]
For testing purposes, we should set up TYPO3 on two DigitalOcean servers.
As they don't offer a TYPO3 image, I would spin up the server with a Linux distribution of your choice, you install TYPO3 and everything, and I then store that as an image for additional servers.

**Comment by drdla** [comment]
First server is up with Debian 7 now.

**Comment by OlegHainulin-ScienceSoft** [comment]
Intsalled apache2 (2.2.22-13+deb7u4), php5 (5.4.36-0+deb7u3), mysql-server (5.5.41-0+wheezy1)
installed typo3 v. 4.5.39 LTS
