### ISSUE TITLE
Provide Typo3 credentials for LaterPay API

### ISSUE THREAD

**Issue by VadzimBelski-ScienceSoft** [laterpay/laterpay-typo3-extension#25]
We should generate a new set of Sandbox credentials for a merchant called 'LaterPay-TYPO3Demo' that can be distributed with the TYPO3 extension.

**Comment by twoldrich** [comment]
The **sandbox credentials** are
**Sandbox Merchant ID**: Eg8gBKoNZuMGy5gSLmPAi5
**Sandbox API Key**: 2053408a5beb4c19844f9b0849c9bbd5

@VadzimBelski-ScienceSoft As the Merchant ID has to have 22 characters, the proposed merchant ID is not possible (and it's not that easy to change the Merchant ID, so lets just use a regular set of of API credentials). Please close, if ok.

**Comment by VadzimBelski-ScienceSoft** [comment]
@twoldrich i will close while be sure this credentials working. I will keep it assigned to me.
