### ISSUE TITLE
Integrate PHPCS with Travis

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-typo3-extension#3]
TYPO3 coding standards should be enforced using PHPCS with the official TYPO3 ruleset:
https://github.com/typo3-ci/TYPO3CMS

**Comment by VadzimBelski-ScienceSoft** [comment]
@OlegHainulin-ScienceSoft please update current status

**Comment by OlegHainulin-ScienceSoft** [comment]
build script done
