### ISSUE TITLE
Purchase Dialog Doesn't Show Title 

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-typo3-extension#60]
The purchase dialog doesn't show a title – from my point of view, it should display the title of the respective page.

![image](https://cloud.githubusercontent.com/assets/6638286/7203144/b48c16e2-e518-11e4-87a2-5cd6a4f14373.png)

@mturalenka Please feel free to assign the ticket.

**Comment by mturalenka** [comment]
seems that missing or empty title param transferred to php client to get buy/add  purchase url. @OlegHainulin-ScienceSoft  please take a look

**Comment by OlegHainulin-ScienceSoft** [comment]
As title for content used header field:
![image 1](https://cloud.githubusercontent.com/assets/1344205/7275150/caf09840-e90a-11e4-8e09-7e34eaceb1fa.png)

**Comment by twoldrich** [comment]
@OlegHainulin-ScienceSoft Thanks for the explanation, I thought the page title would be used.
