### ISSUE TITLE
Update Dashboard Statistic functionality

### ISSUE THREAD

**Issue by mturalenka** [laterpay/laterpay-typo3-extension#65]
according to the fixes made in wordpress plugin need to update typo3 plugin:
https://github.com/laterpay/laterpay-wordpress-plugin/issues/731

**Comment by yastapenko-ScnSoft** [comment]
1) in typo3 plugin we can't track timepass buying  from content, but we can track timepass from page.
2) Visitor come to page, not to content - so we can't track content views at all, we can track only page views. 
3) Page can have more than one purchasable content
@mturalenka - seems like we can't update statistic as in wordpress plugin, so need to clarify what exactly we will update

**Comment by yastapenko-ScnSoft** [comment]
@drdla as we discussed with @mturalenka there is way to do statistics like in wordpress plugin. For this we need to track views for every content block, for example if there are 5 purchasable content blocks on page - then we will track not one page view, but 5 content views. Then we will be able to do statistics as in wordpress. Problem is that visit on one page is not visit to five different contents, but page can have multiply purchasable content blocks. So will idea described upper is acceptable or, probably you have some ideas?
