### ISSUE TITLE
Truncate laterpay post views table periodically

### ISSUE THREAD

**Issue by mturalenka** [laterpay/laterpay-typo3-extension#69]
That table can grow quite large. We should prevent it from becoming too large.
One option would be to truncate all records that are older than 3 month, because those won´t be analysed by our statistics feature anyway. 
https://github.com/laterpay/laterpay-wordpress-plugin/issues/16

**Comment by yastapenko-ScnSoft** [comment]
Added task for typo3 schedule. Need to add this task into list from admin part

**Comment by mturalenka** [comment]
@yastapenko-ScnSoft is it possible to do that programmatically?

**Comment by drdla** [comment]
The table should be truncated after 3 months.

**Comment by mturalenka** [comment]
@drdla apologies, updated description. @yastapenko-ScnSoft please fix
