### ISSUE TITLE
Set up Gulp

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-typo3-extension#7]

**Comment by VadzimBelski-ScienceSoft** [comment]
@OlegHainulin-ScienceSoft  this issue closely connected to https://github.com/laterpay/laterpay-typo3-extension/issues/8#issuecomment-77123424 "res" folder. Please setup Glup asap and remove useless folder.

**Comment by OlegHainulin-ScienceSoft** [comment]
in progress

**Comment by VadzimBelski-ScienceSoft** [comment]
Latest version for WordPress plugin: https://github.com/laterpay/laterpay-wordpress-plugin/blob/master/gulpfile.js
