### ISSUE TITLE
Capabilities for users with role "editor"

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-typo3-extension#71]
Everything else unchanged, users with role "editor" should be able to
- make content paid content (i.e. set a price for it) and
- preview paid content as it appears for visitors or admins

**Comment by yastapenko-ScnSoft** [comment]
As you know in typo3 allowed access to extension, i.e. to all functional at all. Does this task mean that any editor must have access to extension, or that for users with different roles background must work in different ways?

**Comment by drdla** [comment]
Yes - editors should have the same rights as admins

**Comment by yastapenko-ScnSoft** [comment]
And the problem is that there is no any possibilities to determine which group - is editors. Because names can be absolutely different, and user groups is configurable - so they might be configured in any way...

**Comment by yastapenko-ScnSoft** [comment]
only if all usergroups in admin part is editors, then we can provide access to laterpay admin tools.

**Comment by yastapenko-ScnSoft** [comment]
@drdla so, what will we do?

**Comment by mturalenka** [comment]
perhaps we can allow admin to choose in settings what groups are `editors`?

**Comment by drdla** [comment]
I have asked them specifically, what their group is called and got no answer so far.
So we`ll have to put this on hold until then.

**Comment by twoldrich** [comment]
the name of this user role is "redakteur"

**Comment by twoldrich** [comment]
@mturalenka Can you please estimate, when this can be done? The customer just asked me about that ticket.

**Comment by mturalenka** [comment]
@twoldrich i added options on plugin backend(Appearance page -> Select Admin User Group) to select admin groups that can
- so if these groups have access to post(web page) they could modify price
- these groups will have possibility to view page as Admin/Visitor

to allow access to plugin pages(Pricing,Appearance etc) should be grunted access via `User Admin` settings to whole plugin and they should be within our admin group list. 
i can grunt access to whole plugin for such groups automatically, after selection admin groups, should i do this?
