### ISSUE TITLE
Prevent TYPO3 to insert random <p class="bodytext"></p>

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-typo3-extension#74]
I found that TYPO3 injects a lot of paragraphs into our views that break the appearance.

For example in wrap.html inside of `<div class="lp_benefits">` and `<div class="lp_poweredBy">`.

**Comment by yastapenko-ScnSoft** [comment]
@drdla can you clarify details? Did you talk about user part, and if so, can you clarify rising conditions, because i can't reproduce on locale

**Comment by drdla** [comment]
I've answered in Slack. Clear now?

**Comment by yastapenko-ScnSoft** [comment]
@drdla not exactly, Which type of preview selected? About link on site - Authorization Required

**Comment by yastapenko-ScnSoft** [comment]
@drdla seems like wrapping some content in paragraph is configured through setup typoscript and can be configured in different ways for different sites. And seems like we can't do something with that.
