### ISSUE TITLE
Remove unnecessary UI elements

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-typo3-extension#76]
I compiled a list of UI elements, which should be **removed** from the current Typo3 plugin backend as those features are not available in the plugin currently. @yastapenko-ScnSoft please have a look at the list and check, if the functionality is indeed not available in the current Typo3 plugin before removing the according UI elements.
## Pricing Tab:
- Toggle for "time passes only mode":
  ![screenshot 2015-05-05 13 58 20](https://cloud.githubusercontent.com/assets/6638286/7472975/ce579eac-f337-11e4-83b0-762cb89a3134.png)
- Global Default Price:
  ![screenshot 2015-05-05 13 59 10](https://cloud.githubusercontent.com/assets/6638286/7472980/dd80c91c-f337-11e4-8b42-de5b0cbdff52.png)
- URL input for gift cards: 
  ![screenshot 2015-05-05 13 59 29](https://cloud.githubusercontent.com/assets/6638286/7472985/e54b70fc-f337-11e4-8f49-14d55dce77bc.png)
- Bulk Price Editor:
  ![screenshot 2015-05-05 13 59 48](https://cloud.githubusercontent.com/assets/6638286/7472990/eba9ec30-f337-11e4-8864-109c92f01e93.png)
## Appearance Tab:
- Gift Card Section:
  ![screenshot 2015-05-05 14 00 15](https://cloud.githubusercontent.com/assets/6638286/7472996/f69f80e6-f337-11e4-9369-9f6e0c3dfb42.png)
- Content Rating:
  ![screenshot 2015-05-05 14 01 02](https://cloud.githubusercontent.com/assets/6638286/7473003/ff204de0-f337-11e4-893c-ff0f553da0b5.png)
- Premium Shortcode Section:
  ![screenshot 2015-05-05 14 01 27](https://cloud.githubusercontent.com/assets/6638286/7473009/06fd4de2-f338-11e4-8c90-0d5201b75f10.png)
- Integration into Theme section:
  ![screenshot 2015-05-05 14 07 06](https://cloud.githubusercontent.com/assets/6638286/7473014/0fc351ce-f338-11e4-853e-f1d54aaeb818.png)
## Dashboard:

@yastapenko-ScnSoft  I'm not sure, which part of the dashboard is actually working / supposed to work. Could you provide further information about that, please?

**Comment by yastapenko-ScnSoft** [comment]
@twoldrich Dashboard must work correctly but some problems could arise on merge etc.

**Comment by yakau** [comment]
Just FYI, you're copying me into this - I think accidentally. I've received two "[laterpay-typo3-extension] Remove unnecessary UI elements (#76)" emails from github in the past few days.

I've never user Laterpay.

yastapenko-ScnSoft uses the Yakau nickname, the same as me, which I think is where the confusion is coming from.

https://github.com/yakau
https://github.com/yastapenko-ScnSoft

are two different people.

**Comment by twoldrich** [comment]
Thank you for the hint – sorry for the mistake!

**Comment by yakau** [comment]
Forget about it. Best of luck with your work!
