### ISSUE TITLE
Settings management

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-typo3-extension#8]
As an admin,
I should be able to manage relevant settings from the TYPO3 backend, such as time passes configuration, extension mode, and API credentials,
so I can configure the extension according to my needs.

**Comment by VadzimBelski-ScienceSoft** [comment]
@drdla  We will use UI as is from Wordpress plugin ? However we can see some risk here. Does UI should look like the same as Wordpress UI ? Or should we assume standard interface with TYPO3 forms etc ?

**Comment by VadzimBelski-ScienceSoft** [comment]
Oleg plan for today:
- take assets from Wordpress and place in Typo3
- Load Bootstrap from Wordpress in Typo3 module. utilize admin templates from Wordpress in Typo3
- Deploy results on test server
- Install TemplaVoila with flexible content elements (FCE) and piBase extensions

**Comment by VadzimBelski-ScienceSoft** [comment]
The idea is to use existing Wordpress functionality for 
- MVC Structure
- Core
- Views
- Assets
- Logger

We will created custom
- Controllers
- Helpers
- Models
- Config

**Comment by VadzimBelski-ScienceSoft** [comment]
@OlegHainulin-ScienceSoft  and @yastapenko-ScnSoft  please key value schema for configuration.
Please put here configution VARIABLES and their defaults.

**Comment by VadzimBelski-ScienceSoft** [comment]
- function for translation + xml file with translations
- correct not found images and css
- correct console errors

**Comment by VadzimBelski-ScienceSoft** [comment]
- we have a problem in UI because of missing styles from Wordpress css (this not required for now)
- Oleg we need controllers and ajax call (first step is account controllers and Ajax calls)
- Second step is Pricing controllers and Ajax calls
- "res" should be out of the git and called more appropriate "built_assets" . This sources should not be in git. Ignore this folder in gitignore #6

**Comment by VadzimBelski-ScienceSoft** [comment]
Status:
- account page saving settings
- pricing page in 
- "res" changes not done
