### ISSUE TITLE
Social media Plugin not working with LaterPay plugin

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-typo3-extension#84]
A merchant says that his social media plugin (it shows a social media bar **below** each article) is not working anymore, the bar is not displayed. There now is a Javascript error 

> "$(...).socialSharePrivacy is not a function".

Their admin said it might be because of the LaterPay plugin.
@mturalenka Could you please assign that ticket? It would be good to have that solved soonish.

**Comment by mturalenka** [comment]
@twoldrich what's a plugin?

**Comment by mturalenka** [comment]
fixed via 50a5a12dd43c20a778724015fb7f54d51d7971a6

**Comment by twoldrich** [comment]
The extension is called "socialshareprivacy".

**Comment by twoldrich** [comment]
@mturalenka Could you also please estimate, how long it would take to fix that?
