### ISSUE TITLE
Individual teaser is replaced by automatic teaser when saving for the first time

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-typo3-extension#86]
A customer reports, that the teaser content is replaced by an automatically generated teaser when saving the content for the first time. After changing the teaser again, the individual teaser is saved as expected.

@mturalenka Could you please assign this ticket?

**Comment by twoldrich** [comment]
The customer just added, that the saving behaviour for the teaser is very "unstable": Sometimes the teaser is saved correctly, sometimes it's replaced by the automatically generated teaser.

**Comment by mturalenka** [comment]
@twoldrich i could not reproduce on our test server, could you please try?
currently we have next behavior: if teaser field is empty - we generate excerpt from content, if not empty  - we leave as is.

**Comment by twoldrich** [comment]
@mturalenka I could reproduce the following behavior:
- Create new content
- Fill in the teaser field
- Save the post
- Save the post again => Teaser is replaced

**Comment by mturalenka** [comment]
@twoldrich got it, thank you.
