### ISSUE TITLE
Teaser content is shortened

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-typo3-extension#88]
The customer just reported, that the teaser (the text from the teaser text input, not the text under the overlay) is shortened: Only 10% of what's defined as teaser is actually displayed, followed by "...".
It seems, that for the teaser, the same length rules are applied as for the text under the overlay.
The correct behaviour would be, that the teaser is displayed in it's full length and only the text under the overlay follows the rules definded in the "Appearance" section.

@mturalenka Could you please have a look and assign accordingly?

**Comment by mturalenka** [comment]
sure will take a look
