### ISSUE TITLE
Preview and full access to paid content

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-typo3-extension#9]
As a user,
I should see a preview version of the content plus a purchase button before I have purchased a piece of paid content and only get full access to the content after I have completed the purchase,
so I can get an impression of the premium content before purchase.

The preview content should be defined manually in an additional “teaser content” field that is integrated with the add / edit content page.

**Comment by VadzimBelski-ScienceSoft** [comment]
Yakau
- On test server i created test page for you. http://178.62.214.75/examples/laterpay/
- Please extend content editing for any content types (Later content types should be defined in terms of #8 ticket)
- Review Wordpress teaser implementation https://github.com/laterpay/laterpay-wordpress-plugin/blob/master/laterpay/application/Controller/Post.php#L911

**Comment by VadzimBelski-ScienceSoft** [comment]
We agreed in this ticket
- we need to complete admin function, extend content types and add tipsier field, and input field for global price - _status: done_
- we need hook our content before its shown to user, and we need to show teaser and purchase button in stead of content, this is rendered on server side. - _status: done_

**Comment by VadzimBelski-ScienceSoft** [comment]
- investigate if its possible to add special block - _status: no its not_
- need to add description to each function - _status: done_
- on front and add button - _status: in progress_

**Comment by VadzimBelski-ScienceSoft** [comment]
Need to add js script so LaterPay button will work

**Comment by yastapenko-ScnSoft** [comment]
Seems like done, but probably some small changes will be needed
